### ISSUE TITLE
User table display user info irrespective of Course score info

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#407]
User table is a combination of user info and course grade info. Ideally, we want these 2 in separate tables. The issues is when there is no course grade info at least the user info should be populated in the table leaving the current and final score to null. This fix is to perform a left join then inner join.

**Comment by pushyamig** [comment]
This is resolved with this PR https://github.com/tl-its-umich-edu/my-learning-analytics/commit/8405cd2beedc70e168484683909c9846996b0f99. I am closing this

**Comment by jennlove-um** [comment]
Testing appears to pass.  Teachers are an example of users who will always have no course grades.  Logging in as a teacher, I can still see all the course visualizations correctly, so this appears to work as intended.
