### ISSUE TITLE
remove addition of UDW_FILE_ID_PREFIX when pulling files info from Canvas DW

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#409]
While pulling the file contextual information from CanvasDW unnecessary prefixing '170000000` is ending up wrong file id entered to the `file` table and when joining with `file access ` table which has files events data resulting in an empty set for a course. Here is the query for it 
```
select concat({settings.UDW_FILE_ID_PREFIX}, canvas_id) as ID, display_name as NAME, course_id as COURSE_ID from file_dim
where file_state ='available'
  and course_id='{UDW_course_id}'
order by canvas_id
```

But instead pull the file id information from CanvasDW would solves the problem
```
select id, display_name as name,course_id as COURSE_ID from file_dim where file_state ='available' 
                           and course_id='{UDW_course_id}'
```

**Comment by andrew-gardener** [comment]
PR #350 should fix the incorrect file id but not relying on environment variables is also better

**Comment by pushyamig** [comment]
The problem is that query need not rely on any sort of prefixing the info is right there in Canvas Datawarehouse so I think my issue is still relevant. We have a production issue because of this so I will open a PR and fix the problem

**Comment by jonespm** [comment]
I think #350 would fix this. The issue is that users input the values as canvas id into the courses table. The table does store the "canvas id" but the call to get_supported_courses only returns the canvas id, not the unizin id.

So we'd need a new method (or parameter) that would return the id with the addition and call that from the cron, or just merge #350 (which should get taken eventually as it probably fixes all of the issues here)

**Comment by jonespm** [comment]
Okay, that's probably fine for this query. However there are potential bugs all over the code related to the incorrect use of this prefix.

**Comment by pushyamig** [comment]
This is ready for testing:

**Comment by jennlove-um** [comment]
The files are showing up now for the course that didn't have them this morning.  Tested as an admin and masquerading as a student.  Files view has data for both.  I also tested with a different course, and files view worked correctly for that as well.

**Comment by jennlove-um** [comment]
The file links are not working for file with the 8 digit ids.

**Comment by jonespm** [comment]
I think this might be because the files are too new and not yet synced to Instructure test? I tested a few and changed the URL from test to prod and it downloaded the files.

**Comment by pushyamig** [comment]
@jennlove-um I have changed the URL's pointing to canvas Prod in the files view. Please test again!

**Comment by jennlove-um** [comment]
I can download the files for ARCH 211 now.
